import "@styles/globals.css"

import Nav from "@components/Nav"
import Provider from "@components/Provider"

export const metadata = {
  title: 'Blog post',
  description: 'Generated by Drashit Dudhaiya',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className="app"  suppressHydrationWarning={true}>
        <Provider>
          <Nav />
          {children}
        </Provider>
      </body>
    </html>
  )
}
